services:
  sample_app_db:
    image: postgres
    container_name: sample_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sample_app_postgres:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
  sample_app_rails_web:
    build:
      context: .
      target: production
      args:
        - APP_NAME=sample_app
        - RAILS_ENV=production
        - NODE_ENV=production
    image: sample_app_rails_web:prd
    container_name: sample_app_rails_web.prd
    volumes:
      - sample_app_tmp:/sample_app/tmp
      - sample_app_public:/sample_app/public
    env_file:
      - .env # test
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - sample_app_db
  sample_app_nginx:
    build:
      context: docker/nginx
    image: sample_app_nginx:prd
    container_name: sample_app_nginx.prd
    volumes:
      - sample_app_tmp:/sample_app/tmp:ro
      - sample_app_public:/sample_app/public:ro
    ports:
      - 80:80
    depends_on:
      - sample_app_rails_web
volumes:
  sample_app_postgres:
  sample_app_tmp:
  sample_app_public:
