services:
  sample_app_db:
    image: postgres
    container_name: sample_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sample_app_postgres:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
  sample_app_rails_web:
    build:
      context: .
      target: development
      args:
        - APP_NAME=sample_app
        - RAILS_ENV=development
        - NODE_ENV=development
    image: sample_app_rails_web:dev
    container_name: sample_app_rails_web.dev
    volumes:
      - ./log:/sample_app/log
      - ./tmp:/sample_app/tmp
    env_file:
      - .env
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - sample_app_db
volumes:
  sample_app_postgres:
