services:
  sample_app_db:
    image: postgres
    container_name: sample_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - sample_app_postgres:/var/lib/postgresql/data
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
  sample_app_web_app:
    build:
      context: .
      target: web_development
      args:
        - APP_ENV=development
    image: sample_app_web_app:dev
    container_name: sample_app_web_app.dev
    volumes:
      - .:/sample_app:cached
      - sample_app_bundle:/usr/local/bundle
    env_file:
      - .env
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - sample_app_db
  sample_app_batch:
    build:
      context: .
      target: batch_development
      args:
        - APP_ENV=development
    image: sample_app_batch:dev
    container_name: sample_app_batch.dev
    volumes:
      - .:/sample_app:cached
      - sample_app_bundle:/usr/local/bundle
    env_file:
      - .env
    tty: true
    stdin_open: true
    depends_on:
      - sample_app_web_app
volumes:
  sample_app_postgres:
  sample_app_bundle:
