services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  sample_app_worker:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    #
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile

    # Overrides default command so things don't shut down after the process ends.
    command: >
      bash -c "rm -f /sample_app/tmp/pids/server.pid && \
      bundle install --jobs $(nproc) && \
      (bundle exec rails db:create || true) && \
      bundle exec rails db:migrate && \
      sleep infinity"
