name: ci

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - '**/*.md'
    branches-ignore:
      - main
      - 'release/**'

env:
  RAILS_ENV: 'test'
  POSTGRES_HOST: 'localhost'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'password'
  POSTGRES_DB: 'test'
  TZ: 'Asia/Tokyo'

jobs:
  rubocop:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    services:
      postgres:
        image: postgres:15.3-alpine3.18
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.node-version'
#          cache: 'yarn'

#      - name: Yarn install
#        run: yarn install --frozen-lockfile

      - name: Cache assets
        uses: actions/cache@v3
        with:
          path: |
            public/assets
            tmp/cache/assets
          key: asset-assets-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            assets-${{ runner.os }}-${{ github.ref }}-${{ github.sha }}
            assets-${{ runner.os }}-${{ github.ref }}-
            assets-${{ runner.os }}-

      - name: Run assets precompile
        run: bundle exec rake assets:precompile --trace

      - name: Setup Database
        run: bundle exec rake parallel:setup --trace

      - name: Run RSpec
        run: bundle exec parallel_rspec
